name: CI

on:
  push:
    branches: [ main, master ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch: {}

jobs:
  test-and-build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-build.txt

      - name: Run unit tests
        run: python -m unittest discover -s tests

      - name: Build executable
        run: python scripts\build_exe.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: WindowTransparencyManager
          path: dist/WindowTransparencyManager.exe
          if-no-files-found: error

  release:
    needs: test-and-build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    permissions:
      contents: write

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: WindowTransparencyManager
          path: dist

      - name: Publish GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/WindowTransparencyManager.exe
          name: Window Transparency Manager ${{ github.ref_name }}
          body: |
            Automated release for `${{ github.ref_name }}`.
            
            包含 PyInstaller 打包生成的 `WindowTransparencyManager.exe`。
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
